server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_dev;MODE=MYSQL
    username: sa
    password: